//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finalödevi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kurs_ogrenci_iliskisi
    {
        public int kursogrenciId { get; set; }
        public Nullable<System.DateTime> kayıt_tarihi { get; set; }
        public string notlar { get; set; }
    
        public virtual Kurslar Kurslar { get; set; }
        public virtual ogrenci ogrenci { get; set; }
    }
}
