//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finalödevi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurslar
    {
        public int kursİd { get; set; }
        public string Kursadi { get; set; }
        public string aciklama { get; set; }
        public string kategorisi { get; set; }
        public string fiyat { get; set; }
    
        public virtual kurs_ogrenci_iliskisi kurs_ogrenci_iliskisi { get; set; }
    }
}
