//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finalödevi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenci
    {
        public int ogrenciId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string eposta { get; set; }
        public string sifre { get; set; }
    
        public virtual kurs_ogrenci_iliskisi kurs_ogrenci_iliskisi { get; set; }
    }
}
